---
_extends: .github

repository:
  name: experimental
  description: Experimental - Anyone can submit anything in here
  has_wiki: true
  allow_merge_commit: true

branches:
  - name: "master"
    protection:
      # No code reviews required in experimental.
      required_pull_request_reviews: null
      required_status_checks:
        contexts:
          - cirrus-ci
          - Hound
