---
_extends: template

repository:
  name: experimental
  description: Experimental - Anyone can submit anything in here
  has_wiki: true
  allow_merge_commit: true

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - cirrus-ci

# Labels specific to this repository.
labels:
  - name: "MOD:bootstrap"
    color: "#01707f"
    description: "Bootstrap"

  - name: "MOD:crypto"
    color: "#1d76db"
    description: "Crypto"

  - name: "MOD:file-transfers"
    color: "#e02abf"
    description: "File Transfers"

  - name: "MOD:messenger"
    color: "#d93f0b"
    description: "Messenger"

  - name: "MOD:network"
    color: "#d4c5f9"
    description: "Network"

  - name: "MOD:toxav"
    color: "#0052cc"
    description: "Audio/video"
