---
_extends: template

repository:
  name: experimental
  description: Experimental - Anyone can submit anything in here
  has_wiki: true
  allow_merge_commit: true

branches:
  - name: "master"
    protection:
      # No code reviews required in experimental.
      required_pull_request_reviews: null
      required_status_checks:
        contexts:
          - WIP
          - cirrus-ci
          - license/cla

# Labels specific to this repository.
labels:
  - name: "bootstrap"
    color: "#01707f"
    description: "Bootstrap"

  - name: "crypto"
    color: "#1d76db"
    description: "Crypto"

  - name: "file transfers"
    color: "#e02abf"
    description: "File Transfers"

  - name: "messenger"
    color: "#d93f0b"
    description: "Messenger"

  - name: "network"
    color: "#d4c5f9"
    description: "Network"

  - name: "toxav"
    color: "#0052cc"
    description: "Audio/video"
