---
cirrus-ci_task:
  container:
    image: toxchat/toktok-stack:0.0.6
    cpu: 2
    memory: 2G
  configure_script:
    - /src/workspace/tools/inject-repo experimental
  test_all_script:
    - bazel test --config=ci --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST -k //experimental/...
