---
bazel-opt_task:
  container:
    image: toxchat/toktok-stack:latest-release
    cpu: 2
    memory: 4G
  configure_script:
    - /src/workspace/tools/inject-repo experimental
  test_all_script:
    - cd /src/workspace && bazel test -k
        --remote_cache=http://$CIRRUS_HTTP_CACHE_HOST
        //experimental/...
