---
name: automerge

on:
  status

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.event.state == 'success'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: automerge
        run: |
          git remote add upstream https://github.com/TokTok/experimental
          echo git push upstream $GITHUB_REF:master
          git push upstream $GITHUB_REF:master
