name: ci

on:
  workflow_dispatch:
  pull_request:
    branches: [master]

# Cancel old builds when pushing new commits.
concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  common:
    uses: TokTok/ci-tools/.github/workflows/common-ci.yml@master

  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - run: cmake -B _build
      - run: cmake --build _build
      - run: cmake --install _build
