name: deploy

on:
  # Allow manual trigger.
  workflow_dispatch:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]
    tags: ["v*"]

# Cancel old builds when pushing new commits.
concurrency:
  group: deploy-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  #############################################################
  # Preparation jobs
  #############################################################

  prepare:
    name: Prepare
    uses: TokTok/ci-tools/.github/workflows/deploy-prepare.yml@master

  #############################################################
  # Deploy jobs
  #############################################################

  hello:
    name: Hello
    uses: TokTok/ci-tools/.github/workflows/deploy-artifact.yml@master
    with:
      project-name: Experimental
      artifact-source:
        h*llo-{world,welt}.t*t
        listing.txt
      artifact-versioned:
        h*llo-$VERSION-{world,welt}.t*t
        listing-$VERSION.txt
      build: hello
      run: |
        echo "# File listing" >listing.txt

        echo "Hello, world from $GITHUB_SHA on $(date)!" >hello-world.txt
        echo "hello-world.txt" >>listing.txt

        echo "Hallo, Welt von $GITHUB_SHA am $(date)!" >hallo-welt.txt
        echo "hallo-welt.txt" >>listing.txt
