name: deploy

on:
  # Allow manual trigger.
  workflow_dispatch:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]
    tags: ["v*"]

# Cancel old builds when pushing new commits.
concurrency:
  group: deploy-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  #############################################################
  # Preparation jobs
  #############################################################

  prepare:
    name: Prepare
    uses: iphydf/ci-tools/.github/workflows/deploy-prepare.yml@multi-artifact

  #############################################################
  # Deploy jobs
  #############################################################

  hello:
    name: Hello
    uses: iphydf/ci-tools/.github/workflows/deploy-artifact.yml@multi-artifact
    with:
      project-name: Experimental
      artifact-source: h*llo-{world,welt}.t*t
      artifact-versioned: h*llo-$VERSION-{world,welt}.t*t
      build: hello
      run: |
        echo "Hello, world from $GITHUB_SHA on $(date)!" >hello-world.txt
        echo "Hallo, Welt von $GITHUB_SHA am $(date)!" >hallo-welt.txt
