name: deploy

on:
  # Allow manual trigger.
  workflow_dispatch:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]
    tags: ["v*"]

# Cancel old builds when pushing new commits.
concurrency:
  group: deploy-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  #############################################################
  # Preparation jobs
  #############################################################

  prepare:
    name: Prepare
    uses: iphydf/ci-tools/.github/workflows/deploy-prepare.yml@multi-artifact

  hello:
    name: Hello
    uses: iphydf/ci-tools/.github/workflows/deploy-artifact.yml@multi-artifact
    with:
      project-name: Experimental
      artifact-source: hello-{world,you}.txt
      artifact: hello-$VERSION-{world,you}.txt
      build: hello
      run: |
        echo "Hello, world from $GITHUB_SHA on $(date)!" >hello-world.txt
        echo "Hello, you from $GITHUB_SHA on $(date)!" >hello-you.txt
