name: docker

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# Cancel old builds when pushing new commits.
concurrency:
  group: docker-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  NAMESPACE: toktok

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:.netlify"
          tags: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/experimental:latest
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.NAMESPACE }}/experimental:latest
          cache-to: type=inline
          push: ${{ github.event_name == 'push' }}
