name: pages

on:
  push:
    branches: ["master"]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: read
      id-token: write
      pages: write

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Build documentation
        run: |
          mkdir -p build/web
          echo "<h1>Hello, world!</h1>" >build/web/index.html

      - name: Set-up Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
