name: release

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master
  # pull_request_target event is required for autolabeler to support PRs from forks
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  draft:
    uses: iphydf/ci-tools/.github/workflows/release-drafter.yml@release-drafter
