name: release

on:
  workflow_dispatch:

# Cancel old builds when pushing new commits.
concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:

  release:
    name: Release
    uses: iphydf/ci-tools/.github/workflows/release-deploy.yml@release-wf
    with:
      production: true
