name: release

on:
  push:
    branches: [master]
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  release:
    uses: iphydf/ci-tools/.github/workflows/release-drafter.yml@release-drafter
